### ISSUE TITLE
Travis borked

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-cli#35]
Can't even install with `apt`

![screenshot from 2018-08-12 23-31-57](https://user-images.githubusercontent.com/308049/44006652-fdffa0ba-9e87-11e8-8321-164ae6d09a19.png)

This used to work well :cry:

**Comment by ralphtheninja** [comment]
@r10s It would be really awesome if `deltachat` had its own infrastructure for CI.

**Comment by ralphtheninja** [comment]
> @ralphtheninja you mean to replace the travis server by our own?

Yes.

**Comment by ralphtheninja** [comment]
Ok, now this works, but instead we are having problems with `libetpan-dev`. This is annoying.

**Comment by r10s** [comment]
can't we use the libetpan version from the source?
or is it already used? (https://github.com/deltachat/deltachat-core#build says it's used by default, however)

**Comment by ralphtheninja** [comment]
> can't we use the libetpan version from the source?

No, we can't. Because `deltachat-core` contains symlinks which npm filters out during `npm publish`. So, currently `libetpan-dev` needs to be installed system wide.

Also see

* https://github.com/deltachat/deltachat-node/issues/66
* https://github.com/deltachat/deltachat-core/issues/232

**Comment by r10s** [comment]
@ralphtheninja ahh, i see. the symlinks are all in https://github.com/deltachat/deltachat-core/tree/master/libs/libetpan/include/libetpan , right?

maybe we should just adapt the [update-libetpan.sh script](https://github.com/deltachat/deltachat-core/blob/master/libs/update-libetpan.sh) to copy the headers as files instead of using symlinks. just [removing -a from the copy command](https://github.com/deltachat/deltachat-core/blob/master/libs/update-libetpan.sh#L76) should do this hack :)
the result would be duplicated header files, however, as they are created by script this won't be a big deal - and we can add a big CAVE! hint to the update script to document what we were doing and why.

**Comment by ralphtheninja** [comment]
@r10s Aaah copying is probably much better than my solution! https://github.com/deltachat/deltachat-core/pull/236

**Comment by ralphtheninja** [comment]
> @ralphtheninja ahh, i see. the symlinks are all in https://github.com/deltachat/deltachat-core/tree/master/libs/libetpan/include/libetpan , right?

Correct. It's the only place with symlinks.

> maybe we should just adapt the update-libetpan.sh script to copy the headers as files instead of using symlinks. just removing -a from the copy command should do this hack :)

I didn't know about this script. Cool! :+1:

**Comment by ralphtheninja** [comment]
https://github.com/deltachat/deltachat-cli/commit/85b2b46a9b44392b8da7730c9048ae374e66f620
