### ISSUE TITLE
Sending empty messages

### ISSUE THREAD

**Issue by ralphtheninja** [deltachat/deltachat-cli#39]
Hitting enter on an empty line should not send an empty message

**Comment by ralphtheninja** [comment]
Also, I just noticed by accident that _if_ you send an empty message. The receiver will get a "Chat: " prepended to the empty message and the lock state is set to _zero_. See below, two clients sending empty messages back and forth:

![screenshot from 2018-08-15 16-16-06](https://user-images.githubusercontent.com/308049/44152722-8f31dede-a0a6-11e8-9211-898b48ea8ef5.png)

@r10s I'm not sure if this means anything or not. Just some general info.

**Comment by ralphtheninja** [comment]
https://github.com/deltachat/deltachat-cli/commit/b2418ec39015c7d650b177f61eef8add0c0bab42

**Comment by r10s** [comment]
thanks for the info, i think this is okay-ish.

in the source there is a comment that say, the caller should take care of not to send empty texts, i've added this also to dc_send_text_msg(), see https://github.com/deltachat/deltachat-core/commit/bbb5c3136ed5140aaed472bb44fc9791d1320fe9 . not sure what the initial intension was about this.

that on the receivers side, the text reads "Chat:" is because, if the body does not contain any text, the lib uses the text from the subject, only the prefix in this case.
